### ISSUE TITLE
Tiến trình dịch

### ISSUE THREAD

**Issue by tobedecided0601** [sveltevietnam/learn.svelte.dev#1]
> [!IMPORTANT]
> Issue gốc ở đây https://github.com/sveltevietnam/sveltevietnam.dev/issues/149

## Part 1. Basic Svelte

```[tasklist]
- [x] https://github.com/sveltevietnam/learn.svelte.dev/issues/43
- [x] https://github.com/sveltevietnam/learn.svelte.dev/issues/44
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/4
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/5
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/6
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/7
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/8
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/9
```

## Part 2. Advanced Svelte

```[tasklist]
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/10
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/11
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/12
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/13
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/14
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/15
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/16
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/17
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/18
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/19
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/20
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/21
```

## Part 3. Basic SvelteKit

```[tasklist]
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/22
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/23
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/24
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/25
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/26
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/27
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/28
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/29
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/30
```
  
## Part 4. Advanced SvelteKit

```[tasklist]
### Tasks
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/31
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/32
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/33
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/34
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/35
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/36
- [ ] https://github.com/sveltevietnam/learn.svelte.dev/issues/37
```

**Comment by vnphanquang** [comment]
Cảm ơn @sorae42. Nếu được hãy tách nhỏ từng phần thành mỗi Pull request nhé :pray:

**Comment by vnphanquang** [comment]
Một số kinh nghiệm dịch từ team Svelte Japan: https://github.com/sveltejs/learn.svelte.dev/issues/158#issuecomment-1488335132

**Comment by vnphanquang** [comment]
@sorae42 mình đang tạo ra mỗi issue cho mỗi task list item ở issue description trên để giúp track công việc dễ hơn, và tránh trùng lặp công việc giữa nhiều người. Khi dịch phần nào bạn hãy tự assign mình vào issue tương ứng và tạo PR track issue đó nhé. Xin cảm ơn :pray:
