### ISSUE TITLE
Deploy to Cloudflare

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/learn.svelte.dev#38]
Tạm thời, chúng ta sẽ deploy trang dịch này sang `learn.sveltevietnam.dev` (vì hạ tầng của Svelte Vietnam hiện đang nằm toàn bộ ở đấy).

Sau khi công việc dịch được hoàn thành ta sẽ thảo luận với team Svelte để quyết định có nên dời domain thành subdomain ở `svelte.dev` hay ko (vi.learn.svelte.dev). Khả năng cao là không vì sẽ đòi hỏi việc bảo trì và tương tác giữa cả hai phía core Svelte team và Svelte Vietnam team. Các cộng đồng khác:
- Svelte Nhật Bản hiện cũng đang deploy ở domain riêng `svelte.ja`
- Svelte Pháp tương tự tại `sveltefr.dev`

```[tasklist]
### Tasks
- [ ] nên disallow cả trang ở robots.txt để tránh bị index bởi search engine? - tạm thời ko cần
- [x] sửa svelte kit adapter sang cloudflare
- [x] test tính tương thích của trang với cloudflare
```
